# Generated by Django 3.2.9 on 2021-11-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_alter_passenger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
