# Generated by Django 3.2.9 on 2021-11-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0005_alter_passenger_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='user',
            new_name='username',
        ),
    ]
